version: '3.3'
services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: simple_laravel_books_api
        container_name: simple_laravel_books_api
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./.env.example:/var/www/.env
            - ./:/var/www
            - /var/www/vendor
        ports:
            - "8000:8000"
        environment:
            - APP_ENV=local
        networks:
            - app-network

    # Nginx Service
    web:
        image: nginx:alpine
        container_name: simple_laravel_books_api-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    # MySQL Service
    db:
        image: mysql:5.7
        container_name: simple_laravel_books_api-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel_books
            MYSQL_USER: books
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

volumes:
    dbdata:
        driver: local

networks:
    app-network:
        driver: bridge
